version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hodlezz
      - POSTGRES_PASSWORD=hodlezz4dawin
      - POSTGRES_DB=hodlezz_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - auth-service
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - auth-service
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - auth-service
networks:
  auth-service:
    driver: bridge
volumes:
  pg_data:
    driver: local
  rabbit_data:
    driver: local
